export { default as Layout } from './Layout'
export { default as Home } from './home/Home'
export { default as Housing } from './housing/Housing'
export { default as About } from './about/About'
export { default as Error } from './error/Error'